import assert from 'node:assert';
import fs from 'node:fs';
const { default: mw } = await import('./middleware.js');
const { lockPage } = await import('./lock.js');
const base = 'https://spkr.shop';
delete process.env.SITE_PASSWORD;
assert.equal((await mw(new Request(base + '/'))).status, 503, 'no password configured → locked');
process.env.SITE_PASSWORD = 'geminus';
let r = await mw(new Request(base + '/'));
assert.equal(r.status, 401); assert.match(await r.text(), /Password/);
const post = pw => new Request(base + '/unlock', { method: 'POST', body: new URLSearchParams({ password: pw }) });
r = await mw(post('nope'));
assert.equal(r.status, 401); assert.match(await r.text(), /isn’t right/);
r = await mw(post('geminus'));
assert.equal(r.status, 303);
const cookie = r.headers.get('set-cookie'); assert.match(cookie, /HttpOnly/); assert.ok(!cookie.includes('geminus'));
r = await mw(new Request(base + '/assets/geminus.jpg', { headers: { cookie: 'x=1; ' + cookie.split(';')[0] } }));
assert.equal(r.headers.get('x-middleware-next'), '1', 'valid cookie → continue');
r = await mw(new Request(base + '/assets/geminus.jpg'));
assert.equal(r.status, 401, 'assets locked without cookie');
console.log('gate: all checks passed');
